### ISSUE TITLE
The plugin only works for the first level title in the navigation bar

### ISSUE THREAD

**Issue by garylavayou** [oprypin/mkdocs-section-index#11]
If I use the plugin with the following example,
```yaml
nav:
    - Home: index.md
    - H1:
          - H2:
                - doc_to_h2.md
                - H3: doc_to_h3.md
                - ...
```
The `H2` title is still not clickable, and the `H3` and the following subsections are hided in the navigation bar.
