### ISSUE TITLE
`section-index` doesn't work for index pages in the documentation root

### ISSUE THREAD

**Issue by cdwilson** [oprypin/mkdocs-section-index#23]
Given the following nav:

```yaml
nav:
  - Get Started:
      - index.md
  - Installation:
      - installation/index.md
```

I get this:

<img width="1643" alt="image" src="https://github.com/user-attachments/assets/04fef2ec-7a47-4700-9bc4-2767c50478a0">

If I use the built-in [navigation.indexes](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) instead of `section-index` it works correctly:

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/0c4a2e8b-ce9c-485d-8b87-c133c7f87bab">

Is there a way to support this nav layout using `section-index`?
